DATA:
  name: "HAM10000_resized"
  img_size: 256
  num_classes: 7
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "cBN"
  d_cond_mtd: "D2DCE"
  aux_cls_type: "ADC"
  normalize_d_embed: True
  d_embed_dim: 768  # 高解像度のため減少
  apply_g_sn: True
  apply_d_sn: True
  apply_attn: True
  attn_g_loc: [4]
  attn_d_loc: [1]
  z_dim: 112  # 7の倍数に設定
  g_shared_dim: 128
  g_conv_dim: 80  # 高解像度のため増加
  d_conv_dim: 80  # 高解像度のため増加
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 4000
LOSS:
  adv_loss: "hinge"
  cond_lambda: 0.25
  tac_gen_lambda: 0.25
  tac_dis_lambda: 0.25
  m_p: 0.95
  temperature: 0.25
OPTIMIZATION:
  batch_size: 8  # 高解像度のため減少（必要に応じて調整）
  g_lr: 0.00005
  d_lr: 0.0002
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 2
  total_steps: 40000
